// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VisualMemoryProtocol.proto

package com.protocol;

public final class VisualMemoryProtocol {
  private VisualMemoryProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InsertRecordOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 globalUserID = 1;
    boolean hasGlobalUserID();
    int getGlobalUserID();
    
    // required string usreName = 2;
    boolean hasUsreName();
    String getUsreName();
    
    // required string date = 3;
    boolean hasDate();
    String getDate();
    
    // required double k_factor = 4;
    boolean hasKFactor();
    double getKFactor();
  }
  public static final class InsertRecord extends
      com.google.protobuf.GeneratedMessage
      implements InsertRecordOrBuilder {
    // Use InsertRecord.newBuilder() to construct.
    private InsertRecord(Builder builder) {
      super(builder);
    }
    private InsertRecord(boolean noInit) {}
    
    private static final InsertRecord defaultInstance;
    public static InsertRecord getDefaultInstance() {
      return defaultInstance;
    }
    
    public InsertRecord getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_InsertRecord_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_InsertRecord_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 globalUserID = 1;
    public static final int GLOBALUSERID_FIELD_NUMBER = 1;
    private int globalUserID_;
    public boolean hasGlobalUserID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getGlobalUserID() {
      return globalUserID_;
    }
    
    // required string usreName = 2;
    public static final int USRENAME_FIELD_NUMBER = 2;
    private java.lang.Object usreName_;
    public boolean hasUsreName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getUsreName() {
      java.lang.Object ref = usreName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          usreName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUsreNameBytes() {
      java.lang.Object ref = usreName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        usreName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string date = 3;
    public static final int DATE_FIELD_NUMBER = 3;
    private java.lang.Object date_;
    public boolean hasDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          date_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required double k_factor = 4;
    public static final int K_FACTOR_FIELD_NUMBER = 4;
    private double kFactor_;
    public boolean hasKFactor() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public double getKFactor() {
      return kFactor_;
    }
    
    private void initFields() {
      globalUserID_ = 0;
      usreName_ = "";
      date_ = "";
      kFactor_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUsreName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKFactor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, globalUserID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUsreNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, kFactor_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, globalUserID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUsreNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, kFactor_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.protocol.VisualMemoryProtocol.InsertRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.InsertRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.InsertRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.InsertRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.InsertRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.InsertRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.InsertRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.protocol.VisualMemoryProtocol.InsertRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.protocol.VisualMemoryProtocol.InsertRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.InsertRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protocol.VisualMemoryProtocol.InsertRecord prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.protocol.VisualMemoryProtocol.InsertRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_InsertRecord_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_InsertRecord_fieldAccessorTable;
      }
      
      // Construct using com.protocol.VisualMemoryProtocol.InsertRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        globalUserID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        usreName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        kFactor_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protocol.VisualMemoryProtocol.InsertRecord.getDescriptor();
      }
      
      public com.protocol.VisualMemoryProtocol.InsertRecord getDefaultInstanceForType() {
        return com.protocol.VisualMemoryProtocol.InsertRecord.getDefaultInstance();
      }
      
      public com.protocol.VisualMemoryProtocol.InsertRecord build() {
        com.protocol.VisualMemoryProtocol.InsertRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.protocol.VisualMemoryProtocol.InsertRecord buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.protocol.VisualMemoryProtocol.InsertRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.protocol.VisualMemoryProtocol.InsertRecord buildPartial() {
        com.protocol.VisualMemoryProtocol.InsertRecord result = new com.protocol.VisualMemoryProtocol.InsertRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.globalUserID_ = globalUserID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.usreName_ = usreName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.kFactor_ = kFactor_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protocol.VisualMemoryProtocol.InsertRecord) {
          return mergeFrom((com.protocol.VisualMemoryProtocol.InsertRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.protocol.VisualMemoryProtocol.InsertRecord other) {
        if (other == com.protocol.VisualMemoryProtocol.InsertRecord.getDefaultInstance()) return this;
        if (other.hasGlobalUserID()) {
          setGlobalUserID(other.getGlobalUserID());
        }
        if (other.hasUsreName()) {
          setUsreName(other.getUsreName());
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasKFactor()) {
          setKFactor(other.getKFactor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUsreName()) {
          
          return false;
        }
        if (!hasDate()) {
          
          return false;
        }
        if (!hasKFactor()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              globalUserID_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              usreName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              date_ = input.readBytes();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              kFactor_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 globalUserID = 1;
      private int globalUserID_ ;
      public boolean hasGlobalUserID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getGlobalUserID() {
        return globalUserID_;
      }
      public Builder setGlobalUserID(int value) {
        bitField0_ |= 0x00000001;
        globalUserID_ = value;
        onChanged();
        return this;
      }
      public Builder clearGlobalUserID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        globalUserID_ = 0;
        onChanged();
        return this;
      }
      
      // required string usreName = 2;
      private java.lang.Object usreName_ = "";
      public boolean hasUsreName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getUsreName() {
        java.lang.Object ref = usreName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          usreName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUsreName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        usreName_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsreName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        usreName_ = getDefaultInstance().getUsreName();
        onChanged();
        return this;
      }
      void setUsreName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        usreName_ = value;
        onChanged();
      }
      
      // required string date = 3;
      private java.lang.Object date_ = "";
      public boolean hasDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        date_ = value;
        onChanged();
        return this;
      }
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      void setDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        date_ = value;
        onChanged();
      }
      
      // required double k_factor = 4;
      private double kFactor_ ;
      public boolean hasKFactor() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public double getKFactor() {
        return kFactor_;
      }
      public Builder setKFactor(double value) {
        bitField0_ |= 0x00000008;
        kFactor_ = value;
        onChanged();
        return this;
      }
      public Builder clearKFactor() {
        bitField0_ = (bitField0_ & ~0x00000008);
        kFactor_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ProtocolCommunication.InsertRecord)
    }
    
    static {
      defaultInstance = new InsertRecord(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtocolCommunication.InsertRecord)
  }
  
  public interface UpdateRecordOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 globalUserID = 1;
    boolean hasGlobalUserID();
    int getGlobalUserID();
    
    // required string date = 2;
    boolean hasDate();
    String getDate();
    
    // required double k_factor = 3;
    boolean hasKFactor();
    double getKFactor();
  }
  public static final class UpdateRecord extends
      com.google.protobuf.GeneratedMessage
      implements UpdateRecordOrBuilder {
    // Use UpdateRecord.newBuilder() to construct.
    private UpdateRecord(Builder builder) {
      super(builder);
    }
    private UpdateRecord(boolean noInit) {}
    
    private static final UpdateRecord defaultInstance;
    public static UpdateRecord getDefaultInstance() {
      return defaultInstance;
    }
    
    public UpdateRecord getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_UpdateRecord_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_UpdateRecord_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 globalUserID = 1;
    public static final int GLOBALUSERID_FIELD_NUMBER = 1;
    private int globalUserID_;
    public boolean hasGlobalUserID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getGlobalUserID() {
      return globalUserID_;
    }
    
    // required string date = 2;
    public static final int DATE_FIELD_NUMBER = 2;
    private java.lang.Object date_;
    public boolean hasDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          date_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required double k_factor = 3;
    public static final int K_FACTOR_FIELD_NUMBER = 3;
    private double kFactor_;
    public boolean hasKFactor() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getKFactor() {
      return kFactor_;
    }
    
    private void initFields() {
      globalUserID_ = 0;
      date_ = "";
      kFactor_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasGlobalUserID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKFactor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, globalUserID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, kFactor_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, globalUserID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, kFactor_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.protocol.VisualMemoryProtocol.UpdateRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.UpdateRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.UpdateRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.UpdateRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.UpdateRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.UpdateRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.UpdateRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.protocol.VisualMemoryProtocol.UpdateRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.protocol.VisualMemoryProtocol.UpdateRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.UpdateRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protocol.VisualMemoryProtocol.UpdateRecord prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.protocol.VisualMemoryProtocol.UpdateRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_UpdateRecord_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_UpdateRecord_fieldAccessorTable;
      }
      
      // Construct using com.protocol.VisualMemoryProtocol.UpdateRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        globalUserID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        kFactor_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protocol.VisualMemoryProtocol.UpdateRecord.getDescriptor();
      }
      
      public com.protocol.VisualMemoryProtocol.UpdateRecord getDefaultInstanceForType() {
        return com.protocol.VisualMemoryProtocol.UpdateRecord.getDefaultInstance();
      }
      
      public com.protocol.VisualMemoryProtocol.UpdateRecord build() {
        com.protocol.VisualMemoryProtocol.UpdateRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.protocol.VisualMemoryProtocol.UpdateRecord buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.protocol.VisualMemoryProtocol.UpdateRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.protocol.VisualMemoryProtocol.UpdateRecord buildPartial() {
        com.protocol.VisualMemoryProtocol.UpdateRecord result = new com.protocol.VisualMemoryProtocol.UpdateRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.globalUserID_ = globalUserID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.kFactor_ = kFactor_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protocol.VisualMemoryProtocol.UpdateRecord) {
          return mergeFrom((com.protocol.VisualMemoryProtocol.UpdateRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.protocol.VisualMemoryProtocol.UpdateRecord other) {
        if (other == com.protocol.VisualMemoryProtocol.UpdateRecord.getDefaultInstance()) return this;
        if (other.hasGlobalUserID()) {
          setGlobalUserID(other.getGlobalUserID());
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasKFactor()) {
          setKFactor(other.getKFactor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasGlobalUserID()) {
          
          return false;
        }
        if (!hasDate()) {
          
          return false;
        }
        if (!hasKFactor()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              globalUserID_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              date_ = input.readBytes();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              kFactor_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 globalUserID = 1;
      private int globalUserID_ ;
      public boolean hasGlobalUserID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getGlobalUserID() {
        return globalUserID_;
      }
      public Builder setGlobalUserID(int value) {
        bitField0_ |= 0x00000001;
        globalUserID_ = value;
        onChanged();
        return this;
      }
      public Builder clearGlobalUserID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        globalUserID_ = 0;
        onChanged();
        return this;
      }
      
      // required string date = 2;
      private java.lang.Object date_ = "";
      public boolean hasDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      void setDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
      }
      
      // required double k_factor = 3;
      private double kFactor_ ;
      public boolean hasKFactor() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getKFactor() {
        return kFactor_;
      }
      public Builder setKFactor(double value) {
        bitField0_ |= 0x00000004;
        kFactor_ = value;
        onChanged();
        return this;
      }
      public Builder clearKFactor() {
        bitField0_ = (bitField0_ & ~0x00000004);
        kFactor_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ProtocolCommunication.UpdateRecord)
    }
    
    static {
      defaultInstance = new UpdateRecord(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtocolCommunication.UpdateRecord)
  }
  
  public interface GetTop100OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  public static final class GetTop100 extends
      com.google.protobuf.GeneratedMessage
      implements GetTop100OrBuilder {
    // Use GetTop100.newBuilder() to construct.
    private GetTop100(Builder builder) {
      super(builder);
    }
    private GetTop100(boolean noInit) {}
    
    private static final GetTop100 defaultInstance;
    public static GetTop100 getDefaultInstance() {
      return defaultInstance;
    }
    
    public GetTop100 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_GetTop100_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_GetTop100_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.protocol.VisualMemoryProtocol.GetTop100 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.GetTop100 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.GetTop100 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.GetTop100 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.GetTop100 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.GetTop100 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.GetTop100 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.protocol.VisualMemoryProtocol.GetTop100 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.protocol.VisualMemoryProtocol.GetTop100 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.GetTop100 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protocol.VisualMemoryProtocol.GetTop100 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.protocol.VisualMemoryProtocol.GetTop100OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_GetTop100_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_GetTop100_fieldAccessorTable;
      }
      
      // Construct using com.protocol.VisualMemoryProtocol.GetTop100.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protocol.VisualMemoryProtocol.GetTop100.getDescriptor();
      }
      
      public com.protocol.VisualMemoryProtocol.GetTop100 getDefaultInstanceForType() {
        return com.protocol.VisualMemoryProtocol.GetTop100.getDefaultInstance();
      }
      
      public com.protocol.VisualMemoryProtocol.GetTop100 build() {
        com.protocol.VisualMemoryProtocol.GetTop100 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.protocol.VisualMemoryProtocol.GetTop100 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.protocol.VisualMemoryProtocol.GetTop100 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.protocol.VisualMemoryProtocol.GetTop100 buildPartial() {
        com.protocol.VisualMemoryProtocol.GetTop100 result = new com.protocol.VisualMemoryProtocol.GetTop100(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protocol.VisualMemoryProtocol.GetTop100) {
          return mergeFrom((com.protocol.VisualMemoryProtocol.GetTop100)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.protocol.VisualMemoryProtocol.GetTop100 other) {
        if (other == com.protocol.VisualMemoryProtocol.GetTop100.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:ProtocolCommunication.GetTop100)
    }
    
    static {
      defaultInstance = new GetTop100(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtocolCommunication.GetTop100)
  }
  
  public interface Top100OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 globalUserID = 1;
    boolean hasGlobalUserID();
    int getGlobalUserID();
    
    // repeated .ProtocolCommunication.InsertRecord newRecord = 2;
    java.util.List<com.protocol.VisualMemoryProtocol.InsertRecord> 
        getNewRecordList();
    com.protocol.VisualMemoryProtocol.InsertRecord getNewRecord(int index);
    int getNewRecordCount();
    java.util.List<? extends com.protocol.VisualMemoryProtocol.InsertRecordOrBuilder> 
        getNewRecordOrBuilderList();
    com.protocol.VisualMemoryProtocol.InsertRecordOrBuilder getNewRecordOrBuilder(
        int index);
  }
  public static final class Top100 extends
      com.google.protobuf.GeneratedMessage
      implements Top100OrBuilder {
    // Use Top100.newBuilder() to construct.
    private Top100(Builder builder) {
      super(builder);
    }
    private Top100(boolean noInit) {}
    
    private static final Top100 defaultInstance;
    public static Top100 getDefaultInstance() {
      return defaultInstance;
    }
    
    public Top100 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_Top100_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_Top100_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 globalUserID = 1;
    public static final int GLOBALUSERID_FIELD_NUMBER = 1;
    private int globalUserID_;
    public boolean hasGlobalUserID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getGlobalUserID() {
      return globalUserID_;
    }
    
    // repeated .ProtocolCommunication.InsertRecord newRecord = 2;
    public static final int NEWRECORD_FIELD_NUMBER = 2;
    private java.util.List<com.protocol.VisualMemoryProtocol.InsertRecord> newRecord_;
    public java.util.List<com.protocol.VisualMemoryProtocol.InsertRecord> getNewRecordList() {
      return newRecord_;
    }
    public java.util.List<? extends com.protocol.VisualMemoryProtocol.InsertRecordOrBuilder> 
        getNewRecordOrBuilderList() {
      return newRecord_;
    }
    public int getNewRecordCount() {
      return newRecord_.size();
    }
    public com.protocol.VisualMemoryProtocol.InsertRecord getNewRecord(int index) {
      return newRecord_.get(index);
    }
    public com.protocol.VisualMemoryProtocol.InsertRecordOrBuilder getNewRecordOrBuilder(
        int index) {
      return newRecord_.get(index);
    }
    
    private void initFields() {
      globalUserID_ = 0;
      newRecord_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getNewRecordCount(); i++) {
        if (!getNewRecord(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, globalUserID_);
      }
      for (int i = 0; i < newRecord_.size(); i++) {
        output.writeMessage(2, newRecord_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, globalUserID_);
      }
      for (int i = 0; i < newRecord_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, newRecord_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.protocol.VisualMemoryProtocol.Top100 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.Top100 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.Top100 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.Top100 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.Top100 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.Top100 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.Top100 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.protocol.VisualMemoryProtocol.Top100 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.protocol.VisualMemoryProtocol.Top100 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.protocol.VisualMemoryProtocol.Top100 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protocol.VisualMemoryProtocol.Top100 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.protocol.VisualMemoryProtocol.Top100OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_Top100_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protocol.VisualMemoryProtocol.internal_static_ProtocolCommunication_Top100_fieldAccessorTable;
      }
      
      // Construct using com.protocol.VisualMemoryProtocol.Top100.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNewRecordFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        globalUserID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (newRecordBuilder_ == null) {
          newRecord_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          newRecordBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protocol.VisualMemoryProtocol.Top100.getDescriptor();
      }
      
      public com.protocol.VisualMemoryProtocol.Top100 getDefaultInstanceForType() {
        return com.protocol.VisualMemoryProtocol.Top100.getDefaultInstance();
      }
      
      public com.protocol.VisualMemoryProtocol.Top100 build() {
        com.protocol.VisualMemoryProtocol.Top100 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.protocol.VisualMemoryProtocol.Top100 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.protocol.VisualMemoryProtocol.Top100 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.protocol.VisualMemoryProtocol.Top100 buildPartial() {
        com.protocol.VisualMemoryProtocol.Top100 result = new com.protocol.VisualMemoryProtocol.Top100(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.globalUserID_ = globalUserID_;
        if (newRecordBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            newRecord_ = java.util.Collections.unmodifiableList(newRecord_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.newRecord_ = newRecord_;
        } else {
          result.newRecord_ = newRecordBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protocol.VisualMemoryProtocol.Top100) {
          return mergeFrom((com.protocol.VisualMemoryProtocol.Top100)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.protocol.VisualMemoryProtocol.Top100 other) {
        if (other == com.protocol.VisualMemoryProtocol.Top100.getDefaultInstance()) return this;
        if (other.hasGlobalUserID()) {
          setGlobalUserID(other.getGlobalUserID());
        }
        if (newRecordBuilder_ == null) {
          if (!other.newRecord_.isEmpty()) {
            if (newRecord_.isEmpty()) {
              newRecord_ = other.newRecord_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureNewRecordIsMutable();
              newRecord_.addAll(other.newRecord_);
            }
            onChanged();
          }
        } else {
          if (!other.newRecord_.isEmpty()) {
            if (newRecordBuilder_.isEmpty()) {
              newRecordBuilder_.dispose();
              newRecordBuilder_ = null;
              newRecord_ = other.newRecord_;
              bitField0_ = (bitField0_ & ~0x00000002);
              newRecordBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNewRecordFieldBuilder() : null;
            } else {
              newRecordBuilder_.addAllMessages(other.newRecord_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getNewRecordCount(); i++) {
          if (!getNewRecord(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              globalUserID_ = input.readInt32();
              break;
            }
            case 18: {
              com.protocol.VisualMemoryProtocol.InsertRecord.Builder subBuilder = com.protocol.VisualMemoryProtocol.InsertRecord.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNewRecord(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 globalUserID = 1;
      private int globalUserID_ ;
      public boolean hasGlobalUserID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getGlobalUserID() {
        return globalUserID_;
      }
      public Builder setGlobalUserID(int value) {
        bitField0_ |= 0x00000001;
        globalUserID_ = value;
        onChanged();
        return this;
      }
      public Builder clearGlobalUserID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        globalUserID_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .ProtocolCommunication.InsertRecord newRecord = 2;
      private java.util.List<com.protocol.VisualMemoryProtocol.InsertRecord> newRecord_ =
        java.util.Collections.emptyList();
      private void ensureNewRecordIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          newRecord_ = new java.util.ArrayList<com.protocol.VisualMemoryProtocol.InsertRecord>(newRecord_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.protocol.VisualMemoryProtocol.InsertRecord, com.protocol.VisualMemoryProtocol.InsertRecord.Builder, com.protocol.VisualMemoryProtocol.InsertRecordOrBuilder> newRecordBuilder_;
      
      public java.util.List<com.protocol.VisualMemoryProtocol.InsertRecord> getNewRecordList() {
        if (newRecordBuilder_ == null) {
          return java.util.Collections.unmodifiableList(newRecord_);
        } else {
          return newRecordBuilder_.getMessageList();
        }
      }
      public int getNewRecordCount() {
        if (newRecordBuilder_ == null) {
          return newRecord_.size();
        } else {
          return newRecordBuilder_.getCount();
        }
      }
      public com.protocol.VisualMemoryProtocol.InsertRecord getNewRecord(int index) {
        if (newRecordBuilder_ == null) {
          return newRecord_.get(index);
        } else {
          return newRecordBuilder_.getMessage(index);
        }
      }
      public Builder setNewRecord(
          int index, com.protocol.VisualMemoryProtocol.InsertRecord value) {
        if (newRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewRecordIsMutable();
          newRecord_.set(index, value);
          onChanged();
        } else {
          newRecordBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setNewRecord(
          int index, com.protocol.VisualMemoryProtocol.InsertRecord.Builder builderForValue) {
        if (newRecordBuilder_ == null) {
          ensureNewRecordIsMutable();
          newRecord_.set(index, builderForValue.build());
          onChanged();
        } else {
          newRecordBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addNewRecord(com.protocol.VisualMemoryProtocol.InsertRecord value) {
        if (newRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewRecordIsMutable();
          newRecord_.add(value);
          onChanged();
        } else {
          newRecordBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addNewRecord(
          int index, com.protocol.VisualMemoryProtocol.InsertRecord value) {
        if (newRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewRecordIsMutable();
          newRecord_.add(index, value);
          onChanged();
        } else {
          newRecordBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addNewRecord(
          com.protocol.VisualMemoryProtocol.InsertRecord.Builder builderForValue) {
        if (newRecordBuilder_ == null) {
          ensureNewRecordIsMutable();
          newRecord_.add(builderForValue.build());
          onChanged();
        } else {
          newRecordBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addNewRecord(
          int index, com.protocol.VisualMemoryProtocol.InsertRecord.Builder builderForValue) {
        if (newRecordBuilder_ == null) {
          ensureNewRecordIsMutable();
          newRecord_.add(index, builderForValue.build());
          onChanged();
        } else {
          newRecordBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllNewRecord(
          java.lang.Iterable<? extends com.protocol.VisualMemoryProtocol.InsertRecord> values) {
        if (newRecordBuilder_ == null) {
          ensureNewRecordIsMutable();
          super.addAll(values, newRecord_);
          onChanged();
        } else {
          newRecordBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearNewRecord() {
        if (newRecordBuilder_ == null) {
          newRecord_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          newRecordBuilder_.clear();
        }
        return this;
      }
      public Builder removeNewRecord(int index) {
        if (newRecordBuilder_ == null) {
          ensureNewRecordIsMutable();
          newRecord_.remove(index);
          onChanged();
        } else {
          newRecordBuilder_.remove(index);
        }
        return this;
      }
      public com.protocol.VisualMemoryProtocol.InsertRecord.Builder getNewRecordBuilder(
          int index) {
        return getNewRecordFieldBuilder().getBuilder(index);
      }
      public com.protocol.VisualMemoryProtocol.InsertRecordOrBuilder getNewRecordOrBuilder(
          int index) {
        if (newRecordBuilder_ == null) {
          return newRecord_.get(index);  } else {
          return newRecordBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.protocol.VisualMemoryProtocol.InsertRecordOrBuilder> 
           getNewRecordOrBuilderList() {
        if (newRecordBuilder_ != null) {
          return newRecordBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(newRecord_);
        }
      }
      public com.protocol.VisualMemoryProtocol.InsertRecord.Builder addNewRecordBuilder() {
        return getNewRecordFieldBuilder().addBuilder(
            com.protocol.VisualMemoryProtocol.InsertRecord.getDefaultInstance());
      }
      public com.protocol.VisualMemoryProtocol.InsertRecord.Builder addNewRecordBuilder(
          int index) {
        return getNewRecordFieldBuilder().addBuilder(
            index, com.protocol.VisualMemoryProtocol.InsertRecord.getDefaultInstance());
      }
      public java.util.List<com.protocol.VisualMemoryProtocol.InsertRecord.Builder> 
           getNewRecordBuilderList() {
        return getNewRecordFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.protocol.VisualMemoryProtocol.InsertRecord, com.protocol.VisualMemoryProtocol.InsertRecord.Builder, com.protocol.VisualMemoryProtocol.InsertRecordOrBuilder> 
          getNewRecordFieldBuilder() {
        if (newRecordBuilder_ == null) {
          newRecordBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.protocol.VisualMemoryProtocol.InsertRecord, com.protocol.VisualMemoryProtocol.InsertRecord.Builder, com.protocol.VisualMemoryProtocol.InsertRecordOrBuilder>(
                  newRecord_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          newRecord_ = null;
        }
        return newRecordBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ProtocolCommunication.Top100)
    }
    
    static {
      defaultInstance = new Top100(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtocolCommunication.Top100)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtocolCommunication_InsertRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtocolCommunication_InsertRecord_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtocolCommunication_UpdateRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtocolCommunication_UpdateRecord_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtocolCommunication_GetTop100_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtocolCommunication_GetTop100_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtocolCommunication_Top100_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtocolCommunication_Top100_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032VisualMemoryProtocol.proto\022\025ProtocolCo" +
      "mmunication\"V\n\014InsertRecord\022\024\n\014globalUse" +
      "rID\030\001 \001(\005\022\020\n\010usreName\030\002 \002(\t\022\014\n\004date\030\003 \002(" +
      "\t\022\020\n\010k_factor\030\004 \002(\001\"D\n\014UpdateRecord\022\024\n\014g" +
      "lobalUserID\030\001 \002(\005\022\014\n\004date\030\002 \002(\t\022\020\n\010k_fac" +
      "tor\030\003 \002(\001\"\013\n\tGetTop100\"V\n\006Top100\022\024\n\014glob" +
      "alUserID\030\001 \001(\005\0226\n\tnewRecord\030\002 \003(\0132#.Prot" +
      "ocolCommunication.InsertRecordB$\n\014com.pr" +
      "otocolB\024VisualMemoryProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ProtocolCommunication_InsertRecord_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ProtocolCommunication_InsertRecord_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtocolCommunication_InsertRecord_descriptor,
              new java.lang.String[] { "GlobalUserID", "UsreName", "Date", "KFactor", },
              com.protocol.VisualMemoryProtocol.InsertRecord.class,
              com.protocol.VisualMemoryProtocol.InsertRecord.Builder.class);
          internal_static_ProtocolCommunication_UpdateRecord_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ProtocolCommunication_UpdateRecord_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtocolCommunication_UpdateRecord_descriptor,
              new java.lang.String[] { "GlobalUserID", "Date", "KFactor", },
              com.protocol.VisualMemoryProtocol.UpdateRecord.class,
              com.protocol.VisualMemoryProtocol.UpdateRecord.Builder.class);
          internal_static_ProtocolCommunication_GetTop100_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ProtocolCommunication_GetTop100_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtocolCommunication_GetTop100_descriptor,
              new java.lang.String[] { },
              com.protocol.VisualMemoryProtocol.GetTop100.class,
              com.protocol.VisualMemoryProtocol.GetTop100.Builder.class);
          internal_static_ProtocolCommunication_Top100_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_ProtocolCommunication_Top100_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtocolCommunication_Top100_descriptor,
              new java.lang.String[] { "GlobalUserID", "NewRecord", },
              com.protocol.VisualMemoryProtocol.Top100.class,
              com.protocol.VisualMemoryProtocol.Top100.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
